export const OPEN_METEO_URL = "https://api.open-meteo.com/v1/forecast";

export const current = [
  "temperature_2m",
  "relative_humidity_2m",
  "apparent_temperature",
  "is_day",
  "precipitation",
  "rain",
  "showers",
  "snowfall",
  "weather_code",
  "cloud_cover",
  "surface_pressure",
  "wind_speed_10m",
  "wind_direction_10m",
  "wind_gusts_10m",
].join(",");

export const hourly = [
  "temperature_2m",
  "relative_humidity_2m",
  "apparent_temperature",
  "precipitation_probability",
  "precipitation",
  "rain",
  "showers",
  "snowfall",
  "snow_depth",
  "weather_code",
  "cloud_cover",
  "cloud_cover_low",
  "cloud_cover_mid",
  "cloud_cover_high",
  "visibility",
  "wind_speed_180m",
  "wind_speed_120m",
  "wind_speed_80m",
  "wind_speed_10m",
  "wind_direction_10m",
  "wind_direction_80m",
  "wind_direction_120m",
  "wind_direction_180m",
  "wind_gusts_10m",
  "temperature_80m",
  "temperature_120m",
  "temperature_180m",
  "dew_point_2m",
  "uv_index_clear_sky",
  "is_day",
  "sunshine_duration",
  "uv_index",
].join(",");

export const daily = [
  "temperature_2m_max",
  "temperature_2m_min",
  "weather_code",
  "apparent_temperature_max",
  "apparent_temperature_min",
  "rain_sum",
  "showers_sum",
  "precipitation_hours",
  "precipitation_probability_max",
  "snowfall_sum",
  "precipitation_sum",
  "sunrise",
  "sunset",
  "daylight_duration",
  "sunshine_duration",
  "uv_index_max",
  "uv_index_clear_sky_max",
  "wind_speed_10m_max",
  "wind_gusts_10m_max",
  "wind_direction_10m_dominant",
  "wind_speed_10m_mean",
  "wind_gusts_10m_mean",
  "wind_gusts_10m_min",
  "wind_speed_10m_min",
].join(",");

export const units = {
  wind_speed_unit: "mph",
  precipitation_unit: "inch",
  temperature_unit: "fahrenheit",
};
